version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run: pip install --user -r requirements/dev.txt
    run:
      command: echo {FLASK_CONFIG}
      environment:
          FLASK_COFNIG: staging
    deploy:
      steps:
        - checkout
        - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:44b571d0-58f1-4542-abc5-19b8de50ba4d@git.heroku.com/betterbartap.git master

